feat(drop-split): merge draft commits
Merge of the following two (corrupted) commits:

```
 * 2e7595c - XXX WIP feat(drop-split): add DropSplitController draft (4 months ago) <Christian Fobel>
 * c3ab298 - dev(closed-loop): parameterize split direction (4 months ago) <Christian Fobel>
```

The above commits were corrupted, leading to the following error
message when trying to execute any `git` operation involving either of
the commmits:

```
error: inflate: data stream error (incorrect header check)
error: unable to unpack 83bd91e21cb3b2001a5f159a81cfbbabaf646006 header
fatal: loose object 83bd91e21cb3b2001a5f159a81cfbbabaf646006 (stored in .git/objects/83/bd91e21cb3b2001a5f159a81cfbbabaf646006) is corrupt
```

This commit was constructed manually by computing a diff between the
two surrounding commits.  However, it is not possible to differentiate
the changes due to each of the individual source commits.